/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtifactGallery: typeof import('./components/chat/cards/ArtifactGallery.vue')['default']
    CardRenderer: typeof import('./components/chat/CardRenderer.vue')['default']
    ChatPanel: typeof import('./components/chat/ChatPanel.vue')['default']
    ChoiceCard: typeof import('./components/chat/cards/ChoiceCard.vue')['default']
    ConversationList: typeof import('./components/learn/ConversationList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EngineeringCard: typeof import('./components/chat/cards/EngineeringCard.vue')['default']
    EvidenceChips: typeof import('./components/learn/EvidenceChips.vue')['default']
    FeedbackCard: typeof import('./components/chat/cards/FeedbackCard.vue')['default']
    InteractiveCard: typeof import('./components/chat/cards/InteractiveCard.vue')['default']
    MathCard: typeof import('./components/chat/cards/MathCard.vue')['default']
    PracticeCard: typeof import('./components/chat/cards/PracticeCard.vue')['default']
    QuestionCard: typeof import('./components/chat/cards/QuestionCard.vue')['default']
    RecommendationCard: typeof import('./components/chat/cards/RecommendationCard.vue')['default']
    ResizableDrawer: typeof import('./components/common/ResizableDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./components/learn/SidePanel.vue')['default']
    TextCard: typeof import('./components/chat/cards/TextCard.vue')['default']
    ToolTrace: typeof import('./components/chat/ToolTrace.vue')['default']
    UnderstandCard: typeof import('./components/chat/cards/UnderstandCard.vue')['default']
    WarningCard: typeof import('./components/chat/cards/WarningCard.vue')['default']
    WelcomeScreen: typeof import('./components/chat/WelcomeScreen.vue')['default']
  }
}
