"""baseline: full schema

Revision ID: 14af9d9e8982
Revises: 
Create Date: 2026-09-02 19:51:05.502568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14af9d9e8982'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_telemetry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('course_id', sa.String(length=32), nullable=True),
    sa.Column('allowed_tools', sa.String(length=255), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tool_steps', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('tool_failures', sa.Integer(), nullable=False),
    sa.Column('tool_fail_names', sa.String(length=255), nullable=True),
    sa.Column('compressed_chars', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('thinking_chars', sa.Integer(), nullable=False),
    sa.Column('text_chars', sa.Integer(), nullable=False),
    sa.Column('search_calls', sa.Integer(), nullable=False),
    sa.Column('search_results', sa.Integer(), nullable=False),
    sa.Column('search_authority_hits', sa.Integer(), nullable=False),
    sa.Column('search_top_domains', sa.String(length=200), nullable=True),
    sa.Column('bare_numeric', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_telemetry_conversation_id'), 'agent_telemetry', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_telemetry_created_at'), 'agent_telemetry', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_telemetry_user_id'), 'agent_telemetry', ['user_id'], unique=False)
    op.create_table('learning_domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_evidence_created_at'), 'learning_evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_evidence_evidence_type'), 'learning_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_learning_evidence_user_id'), 'learning_evidence', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_covered', sa.Integer(), nullable=False),
    sa.Column('scratchpad', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('learner_type', sa.String(length=32), nullable=True),
    sa.Column('goal_type', sa.String(length=32), nullable=True),
    sa.Column('learning_style', sa.String(length=64), nullable=True),
    sa.Column('cognitive_state', sa.JSON(), nullable=True),
    sa.Column('profile_confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_profiles_user_id'), 'learner_profiles', ['user_id'], unique=True)
    op.create_table('learning_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('goal', sa.String(length=512), nullable=True),
    sa.Column('start_state', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['learning_domains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_projects_user_id'), 'learning_projects', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('card_type', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('gave_answer', sa.Boolean(), nullable=True),
    sa.Column('scaffold_level', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('next_action', sa.String(length=16), nullable=True),
    sa.Column('strategy', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('thinking', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_learning_projects_user_id'), table_name='learning_projects')
    op.drop_table('learning_projects')
    op.drop_index(op.f('ix_learner_profiles_user_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_learning_evidence_user_id'), table_name='learning_evidence')
    op.drop_index(op.f('ix_learning_evidence_evidence_type'), table_name='learning_evidence')
    op.drop_index(op.f('ix_learning_evidence_created_at'), table_name='learning_evidence')
    op.drop_table('learning_evidence')
    op.drop_table('learning_domains')
    op.drop_index(op.f('ix_agent_telemetry_user_id'), table_name='agent_telemetry')
    op.drop_index(op.f('ix_agent_telemetry_created_at'), table_name='agent_telemetry')
    op.drop_index(op.f('ix_agent_telemetry_conversation_id'), table_name='agent_telemetry')
    op.drop_table('agent_telemetry')
    # ### end Alembic commands ###
